// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANYoFWZxQx2xjACYsrXtGLF9GZKlPhOCg',
    appId: '1:694308970318:web:ec3c952f0adcf12128881f',
    messagingSenderId: '694308970318',
    projectId: 'pulse-94821',
    authDomain: 'pulse-94821.firebaseapp.com',
    storageBucket: 'pulse-94821.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhCXlnYEhBldt1k8zZk0ary9gDE0QzQ1g',
    appId: '1:694308970318:android:21c890551754ef3228881f',
    messagingSenderId: '694308970318',
    projectId: 'pulse-94821',
    storageBucket: 'pulse-94821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIjdYWpdc8bwMT0tf5yOU6m6bvZq4Nnxo',
    appId: '1:694308970318:ios:1d510053e3bf1fdd28881f',
    messagingSenderId: '694308970318',
    projectId: 'pulse-94821',
    storageBucket: 'pulse-94821.firebasestorage.app',
    iosBundleId: 'com.pulse.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIjdYWpdc8bwMT0tf5yOU6m6bvZq4Nnxo',
    appId: '1:694308970318:ios:5fdd3198a7c81d9b28881f',
    messagingSenderId: '694308970318',
    projectId: 'pulse-94821',
    storageBucket: 'pulse-94821.firebasestorage.app',
    iosBundleId: 'com.globuli.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANYoFWZxQx2xjACYsrXtGLF9GZKlPhOCg',
    appId: '1:694308970318:web:fac4f1023c1bb06228881f',
    messagingSenderId: '694308970318',
    projectId: 'pulse-94821',
    authDomain: 'pulse-94821.firebaseapp.com',
    storageBucket: 'pulse-94821.firebasestorage.app',
  );
}
